version: 2
updates:
  - package-ecosystem: docker
    directory: /alpine-prestashop-amd64/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-prestashop-armhf/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /alpine-prestashop-aarch64/
    schedule:
      interval: weekly